### ISSUE TITLE
Refine production time estimates

### ISSUE THREAD

**Issue by gentzkow** [gslab-econ/ra-manual#8]
As part of #1, we decided on hour guidelines for the different components of production that are now reflected in the RA manual [here](https://github.com/gslab-econ/ra-manual/wiki/Paper-Production). Looking back at these, they seem to me like some of them may be high, and I'd like to check in on how they compare to reality.

Steps:

(1) Go back through the time logs for the last 4 or so papers we've put through production and record the actual time spent on each task.

(2) Make a list of the places where you think it would be most efficient to cut back total hours if we needed to do so.

From there we can discuss whether we should make revisions to the guidelines.

@jmshapir fyi

**Comment by Shun-Yang** [comment]
@DavidRitzwoller @mengsongouyang @z-y-huang, since we didn't keep the time spent on specific production tasks, we can try to aggregate our estimates on the previous production tasks that we did in the last few rounds of productions. [Here](https://docs.google.com/spreadsheets/d/1byOHuaImGKJU88Wff0ZYARQa7jaGJ2of0AWzl-HmyCQ/edit?usp=sharing) is a google sheet we can coordinate on. 

Here are the previous productions: 
 - Politext: [1](https://github.com/gslab-econ/politext/issues/746), [2](https://github.com/gslab-econ/politext/issues/746)
 - Divergence: [1](https://github.com/gslab-econ/divergence/issues/124), [2](https://github.com/gslab-econ/divergence/issues/77)
 - Uniform pricing: [1](https://github.com/gentzkow/uniform-pricing/issues/195)

Put in your estimates on the tasks that you were assigned/participated. Thanks!

**Comment by DavidRitzwoller** [comment]
@Shun-Yang I'm pretty sure I only have view-only access to this document

**Comment by mengsongouyang** [comment]
Me too.

**Comment by Shun-Yang** [comment]
Good catch - I changed the link, should work now

**Comment by DavidRitzwoller** [comment]
@z-y-huang and I have added our logs to the drive

**Comment by mengsongouyang** [comment]
Mine is also added. Thanks!

**Comment by Shun-Yang** [comment]
Also entered mine in.

**Comment by DavidRitzwoller** [comment]
@gentzkow 

@mengsongouyang, @Shun-Yang, @z-y-huang, and I finished producing updated estimates of the time necessary to complete the production tasks. We revisited the issues for the previous 5 rounds of production and [logged](https://docs.google.com/spreadsheets/d/1byOHuaImGKJU88Wff0ZYARQa7jaGJ2of0AWzl-HmyCQ/edit#gid=0) our estimates of how long it took to complete each task. We looked at the mean and variation in our estimates of the time required for each task, and agreed on updated headline estimates. 

- There is a lot of variation paper to paper, e.g. MATH for divergence is a similar endeavor to PROOF, but requires only a small amount of time for politext.

- Our estimates are conditional on not noticing any major issues, e.g. PLOT can be time consuming if old code needs to be refactored.  

|  Task | Original Time Estimate | Updated Time Estimate |
| -- | -- | -- |
| PRELIM |  4  | 2  |
| EXT | 12  | 4  |
| REF | 8  | 4  |
| PROOF |  16 |  16 |
| FACT | 6  | 6  |
| DEF | 8  | 6  |
| SOURCE | 4  | 1  |
| THANK | 4  |  1 |
| PLOT | 8  | 6  |
| REPLY | 8  |  8 |
| MATH | 8  | 8  |

@jmshapir FYI

**Comment by gentzkow** [comment]
Great. Thanks @DavidRitzwoller. 

I wonder if it wouldn't be more informative to report a "typical range" rather than a point estimate. Based on the data, do you think you could assign ranges to each task that we'd expect to be roughly the 25-75 interval?

**Comment by DavidRitzwoller** [comment]
That makes sense @gentzkow. @mengsongouyang, @z-y-huang, and I added the following confidence intervals to our estimates:

|  Task | Original Time Estimate | Updated Time Estimate |  25% | 75% |
| -- | -- | -- | -- | -- |
| PRELIM |  4  | 2  | 0.5  | 4  |
| EXT | 12  | 4  | 2  |  6 |
| REF | 8  | 4  | 2  |  6 |
| PROOF |  16 |  16 | 8  | 24  |
| FACT | 6  | 6  | 4  | 8  |
| DEF | 8  | 6  | 4  | 8  |
| SOURCE | 4  | 1  | 0.5  | 2  |
| THANK | 4  |  1 | 0.5  | 2 |
| PLOT | 8  | 6  | 4  | 12  |
| REPLY | 8  |  8 | 4  | 12  |
| MATH | 8  | 8  | 2  |  16 |

**Comment by gentzkow** [comment]
Great. Thanks. Let's put the updated point estimates and 25-75 ranges in
the RA manual. From my perspective the task is then clear to close.

**Comment by DavidRitzwoller** [comment]
@gentzkow, @mengsongouyang, and @z-y-huang. I've edited the RA manual to add our updated point estimates and 25-75 ranges [here](https://github.com/gslab-econ/ra-manual/wiki/Paper-Production). Let me know if there is anything that should be changed, otherwise I'll close the issue.    

@jmshapir FYI

**Comment by z-y-huang** [comment]
@DavidRitzwoller:

I think there's a typo for PROOF. It says the expected number of hours is 4.

**Comment by DavidRitzwoller** [comment]
Thanks @z-y-huang. The typo has been edited.

**Comment by gentzkow** [comment]
Looks good. Thanks!

**Comment by DavidRitzwoller** [comment]
**Summary:** In this task we reviewed our the last 5 rounds of production and refined our estimates of the time necessary for each task. Additionally, we added 50% confidence intervals for each estimate. The updated task descriptions are [here](https://github.com/gslab-econ/ra-manual/wiki/Paper-Production).
